### ISSUE TITLE
NotImplementedError returned from Tensorpack 0.9.6 (0.8.8 works)

### ISSUE THREAD

**Issue by drcdr** [NVlabs/ReflectNet#2]
I am trying to run ReflectNet on some of the sample data.  I'm seeing a "NotImplemented" error when trying to call PredictConfig.  I expanded the OfflinePredictor call as:
```
    model_ = model.Model(model.HSHAPE, model.WSHAPE)
    session_init = get_model_loader('data/checkpoint')
    input_names = ['I1', 'I2', 'I3']
    output_names = ['est_lt', 'est_lr', 'I_s', 'I_p']
    predcfg = PredictConfig(model=model_, session_init=session_init, input_names=input_names, output_names=output_names)
    pred = OfflinePredictor(predcfg)
```
model_ and session_init seem to look OK.  The error I get is on the call to PredictConfig:
```
> python eval.py --scale 0.25 --i0 example/bar_input000.ppm --i45 example/bar_input001.ppm --i90 example/bar_input002.ppm --out output/ --prefix bar2
Namespace(i0='example/bar_input000.ppm', i45='example/bar_input001.ppm', i90='example/bar_input002.ppm', out='output/', prefix='cdr', scale=0.25)
Traceback (most recent call last):
  File "eval.py", line 151, in <module>
    main(args)
  File "eval.py", line 95, in main
    predcfg = PredictConfig(model=model_, session_init=session_init, input_names=input_names, output_names=output_names)
  File "C:\Dev\Anaconda3\envs\Dev\lib\site-packages\tensorpack\predict\config.py", line 87, in __init__
    self.input_signature = model.get_input_signature()
  File "C:\Dev\Anaconda3\envs\Dev\lib\site-packages\tensorpack\utils\argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "C:\Dev\Anaconda3\envs\Dev\lib\site-packages\tensorpack\graph_builder\model_desc.py", line 86, in get_input_signature
    inputs = self.inputs()
  File "C:\Dev\Anaconda3\envs\Dev\lib\site-packages\tensorpack\graph_builder\model_desc.py", line 118, in inputs
    raise NotImplementedError()
NotImplementedError
```

I was using tensorflow-nightly-gpu (20190731) and tensorpack 0.9.6. I went ahead and reverted to tensorpack 0.8.8, where the logic in get_inputs_desc is different (no try/except in 0.9.6):
```
try:
    return self._get_inputs()
except NotImplementedError:
    with tf.Graph().as_default() as G:   # create these placeholder in a temporary graph
        inputs = self.inputs()
        for p in inputs:
            assert p.graph == G, "Placeholders returned by inputs() should be created inside inputs()!"
        return [InputDesc.from_placeholder(p) for p in inputs]
```
It now works OK.  Do you know what would have to be done, to modify ReflectNet to support tensorpack 0.9.6?  I'm not that familiar with tensorpack.

**Comment by PatWie** [comment]
The way model are specified has changed. Instead of

https://github.com/NVlabs/ReflectNet/blob/fcd028f047bf9063ac22b78788e1f58a3021f825/ReflectNet/model.py#L66

please use 

https://github.com/tensorpack/tensorpack/blob/fd6d34a76eaf3e61f833d72cae7d77bb3f990fbb/examples/basics/mnist-tflayers.py#L25

Same for `_build_graph` and `_get_optimizer`
